<?xml version="1.0" encoding="utf-8"?><Database Name="Percussion" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=NLTDC01\SQLServer2008;Initial Catalog=Percussion;User ID=pii" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PercussionConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Assets" Member="Assets">
    <Type Name="Asset">
      <Column Name="AssetID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssetTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssetPath" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AssetName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>