//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DemoDB", "FK_OrderApprovals_OrderApprovalStatuses", "OrderApprovalStatuses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication1.OrderApprovalStatuses), "OrderApprovals", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.OrderApprovals), true)]
[assembly: EdmRelationshipAttribute("DemoDB", "FK_OrderApprovals_Orders", "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication1.Orders), "OrderApprovals", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.OrderApprovals), true)]
[assembly: EdmRelationshipAttribute("DemoDB", "FK_OrderDrafts_OrderDraftStatuses", "OrderDraftStatuses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication1.OrderDraftStatuses), "OrderDrafts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.OrderDrafts), true)]
[assembly: EdmRelationshipAttribute("DemoDB", "FK_OrderDrafts_Orders", "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication1.Orders), "OrderDrafts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.OrderDrafts), true)]
[assembly: EdmRelationshipAttribute("DemoDB", "FK_OrderPayments_Orders", "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication1.Orders), "OrderPayments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.OrderPayments), true)]
[assembly: EdmRelationshipAttribute("DemoDB", "FK_OrderPromotions_Orders", "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication1.Orders), "OrderPromotions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.OrderPromotions), true)]
[assembly: EdmRelationshipAttribute("DemoDB", "FK_Orders_OrderStatuses", "OrderStatuses", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebApplication1.OrderStatuses), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.Orders), true)]

#endregion

namespace WebApplication1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DemoDBContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DemoDBContainer object using the connection string found in the 'DemoDBContainer' section of the application configuration file.
        /// </summary>
        public DemoDBContainer() : base("name=DemoDBContainer", "DemoDBContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DemoDBContainer object.
        /// </summary>
        public DemoDBContainer(string connectionString) : base(connectionString, "DemoDBContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DemoDBContainer object.
        /// </summary>
        public DemoDBContainer(EntityConnection connection) : base(connection, "DemoDBContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderApprovals> OrderApprovals
        {
            get
            {
                if ((_OrderApprovals == null))
                {
                    _OrderApprovals = base.CreateObjectSet<OrderApprovals>("OrderApprovals");
                }
                return _OrderApprovals;
            }
        }
        private ObjectSet<OrderApprovals> _OrderApprovals;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderApprovalStatuses> OrderApprovalStatuses
        {
            get
            {
                if ((_OrderApprovalStatuses == null))
                {
                    _OrderApprovalStatuses = base.CreateObjectSet<OrderApprovalStatuses>("OrderApprovalStatuses");
                }
                return _OrderApprovalStatuses;
            }
        }
        private ObjectSet<OrderApprovalStatuses> _OrderApprovalStatuses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderDrafts> OrderDrafts
        {
            get
            {
                if ((_OrderDrafts == null))
                {
                    _OrderDrafts = base.CreateObjectSet<OrderDrafts>("OrderDrafts");
                }
                return _OrderDrafts;
            }
        }
        private ObjectSet<OrderDrafts> _OrderDrafts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderDraftStatuses> OrderDraftStatuses
        {
            get
            {
                if ((_OrderDraftStatuses == null))
                {
                    _OrderDraftStatuses = base.CreateObjectSet<OrderDraftStatuses>("OrderDraftStatuses");
                }
                return _OrderDraftStatuses;
            }
        }
        private ObjectSet<OrderDraftStatuses> _OrderDraftStatuses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderPayments> OrderPayments
        {
            get
            {
                if ((_OrderPayments == null))
                {
                    _OrderPayments = base.CreateObjectSet<OrderPayments>("OrderPayments");
                }
                return _OrderPayments;
            }
        }
        private ObjectSet<OrderPayments> _OrderPayments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderPromotions> OrderPromotions
        {
            get
            {
                if ((_OrderPromotions == null))
                {
                    _OrderPromotions = base.CreateObjectSet<OrderPromotions>("OrderPromotions");
                }
                return _OrderPromotions;
            }
        }
        private ObjectSet<OrderPromotions> _OrderPromotions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Orders> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Orders>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Orders> _Orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderStatuses> OrderStatuses
        {
            get
            {
                if ((_OrderStatuses == null))
                {
                    _OrderStatuses = base.CreateObjectSet<OrderStatuses>("OrderStatuses");
                }
                return _OrderStatuses;
            }
        }
        private ObjectSet<OrderStatuses> _OrderStatuses;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderApprovals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderApprovals(OrderApprovals orderApprovals)
        {
            base.AddObject("OrderApprovals", orderApprovals);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderApprovalStatuses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderApprovalStatuses(OrderApprovalStatuses orderApprovalStatuses)
        {
            base.AddObject("OrderApprovalStatuses", orderApprovalStatuses);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderDrafts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderDrafts(OrderDrafts orderDrafts)
        {
            base.AddObject("OrderDrafts", orderDrafts);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderDraftStatuses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderDraftStatuses(OrderDraftStatuses orderDraftStatuses)
        {
            base.AddObject("OrderDraftStatuses", orderDraftStatuses);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderPayments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderPayments(OrderPayments orderPayments)
        {
            base.AddObject("OrderPayments", orderPayments);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderPromotions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderPromotions(OrderPromotions orderPromotions)
        {
            base.AddObject("OrderPromotions", orderPromotions);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrders(Orders orders)
        {
            base.AddObject("Orders", orders);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderStatuses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderStatuses(OrderStatuses orderStatuses)
        {
            base.AddObject("OrderStatuses", orderStatuses);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoDB", Name="OrderApprovals")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderApprovals : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderApprovals object.
        /// </summary>
        /// <param name="orderApprovalID">Initial value of the OrderApprovalID property.</param>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="orderApprovalStatusID">Initial value of the OrderApprovalStatusID property.</param>
        /// <param name="dateApproved">Initial value of the DateApproved property.</param>
        public static OrderApprovals CreateOrderApprovals(global::System.Int32 orderApprovalID, global::System.Int32 orderID, global::System.Int32 orderApprovalStatusID, global::System.DateTime dateApproved)
        {
            OrderApprovals orderApprovals = new OrderApprovals();
            orderApprovals.OrderApprovalID = orderApprovalID;
            orderApprovals.OrderID = orderID;
            orderApprovals.OrderApprovalStatusID = orderApprovalStatusID;
            orderApprovals.DateApproved = dateApproved;
            return orderApprovals;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderApprovalID
        {
            get
            {
                return _OrderApprovalID;
            }
            set
            {
                if (_OrderApprovalID != value)
                {
                    OnOrderApprovalIDChanging(value);
                    ReportPropertyChanging("OrderApprovalID");
                    _OrderApprovalID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderApprovalID");
                    OnOrderApprovalIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderApprovalID;
        partial void OnOrderApprovalIDChanging(global::System.Int32 value);
        partial void OnOrderApprovalIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                OnOrderIDChanging(value);
                ReportPropertyChanging("OrderID");
                _OrderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderID");
                OnOrderIDChanged();
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderApprovalStatusID
        {
            get
            {
                return _OrderApprovalStatusID;
            }
            set
            {
                OnOrderApprovalStatusIDChanging(value);
                ReportPropertyChanging("OrderApprovalStatusID");
                _OrderApprovalStatusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderApprovalStatusID");
                OnOrderApprovalStatusIDChanged();
            }
        }
        private global::System.Int32 _OrderApprovalStatusID;
        partial void OnOrderApprovalStatusIDChanging(global::System.Int32 value);
        partial void OnOrderApprovalStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateApproved
        {
            get
            {
                return _DateApproved;
            }
            set
            {
                OnDateApprovedChanging(value);
                ReportPropertyChanging("DateApproved");
                _DateApproved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateApproved");
                OnDateApprovedChanged();
            }
        }
        private global::System.DateTime _DateApproved;
        partial void OnDateApprovedChanging(global::System.DateTime value);
        partial void OnDateApprovedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoDB", "FK_OrderApprovals_OrderApprovalStatuses", "OrderApprovalStatuses")]
        public OrderApprovalStatuses OrderApprovalStatuses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderApprovalStatuses>("DemoDB.FK_OrderApprovals_OrderApprovalStatuses", "OrderApprovalStatuses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderApprovalStatuses>("DemoDB.FK_OrderApprovals_OrderApprovalStatuses", "OrderApprovalStatuses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<OrderApprovalStatuses> OrderApprovalStatusesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderApprovalStatuses>("DemoDB.FK_OrderApprovals_OrderApprovalStatuses", "OrderApprovalStatuses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<OrderApprovalStatuses>("DemoDB.FK_OrderApprovals_OrderApprovalStatuses", "OrderApprovalStatuses", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoDB", "FK_OrderApprovals_Orders", "Orders")]
        public Orders Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Orders>("DemoDB.FK_OrderApprovals_Orders", "Orders").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Orders>("DemoDB.FK_OrderApprovals_Orders", "Orders").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Orders> OrdersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Orders>("DemoDB.FK_OrderApprovals_Orders", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Orders>("DemoDB.FK_OrderApprovals_Orders", "Orders", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoDB", Name="OrderApprovalStatuses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderApprovalStatuses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderApprovalStatuses object.
        /// </summary>
        /// <param name="orderApprovalStatusID">Initial value of the OrderApprovalStatusID property.</param>
        /// <param name="orderApprovalStatus">Initial value of the OrderApprovalStatus property.</param>
        public static OrderApprovalStatuses CreateOrderApprovalStatuses(global::System.Int32 orderApprovalStatusID, global::System.String orderApprovalStatus)
        {
            OrderApprovalStatuses orderApprovalStatuses = new OrderApprovalStatuses();
            orderApprovalStatuses.OrderApprovalStatusID = orderApprovalStatusID;
            orderApprovalStatuses.OrderApprovalStatus = orderApprovalStatus;
            return orderApprovalStatuses;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderApprovalStatusID
        {
            get
            {
                return _OrderApprovalStatusID;
            }
            set
            {
                if (_OrderApprovalStatusID != value)
                {
                    OnOrderApprovalStatusIDChanging(value);
                    ReportPropertyChanging("OrderApprovalStatusID");
                    _OrderApprovalStatusID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderApprovalStatusID");
                    OnOrderApprovalStatusIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderApprovalStatusID;
        partial void OnOrderApprovalStatusIDChanging(global::System.Int32 value);
        partial void OnOrderApprovalStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrderApprovalStatus
        {
            get
            {
                return _OrderApprovalStatus;
            }
            set
            {
                OnOrderApprovalStatusChanging(value);
                ReportPropertyChanging("OrderApprovalStatus");
                _OrderApprovalStatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OrderApprovalStatus");
                OnOrderApprovalStatusChanged();
            }
        }
        private global::System.String _OrderApprovalStatus;
        partial void OnOrderApprovalStatusChanging(global::System.String value);
        partial void OnOrderApprovalStatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoDB", "FK_OrderApprovals_OrderApprovalStatuses", "OrderApprovals")]
        public EntityCollection<OrderApprovals> OrderApprovals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderApprovals>("DemoDB.FK_OrderApprovals_OrderApprovalStatuses", "OrderApprovals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderApprovals>("DemoDB.FK_OrderApprovals_OrderApprovalStatuses", "OrderApprovals", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoDB", Name="OrderDrafts")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderDrafts : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderDrafts object.
        /// </summary>
        /// <param name="orderDraftID">Initial value of the OrderDraftID property.</param>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="orderDraftStatusID">Initial value of the OrderDraftStatusID property.</param>
        public static OrderDrafts CreateOrderDrafts(global::System.Int32 orderDraftID, global::System.Int32 orderID, global::System.Int32 orderDraftStatusID)
        {
            OrderDrafts orderDrafts = new OrderDrafts();
            orderDrafts.OrderDraftID = orderDraftID;
            orderDrafts.OrderID = orderID;
            orderDrafts.OrderDraftStatusID = orderDraftStatusID;
            return orderDrafts;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderDraftID
        {
            get
            {
                return _OrderDraftID;
            }
            set
            {
                if (_OrderDraftID != value)
                {
                    OnOrderDraftIDChanging(value);
                    ReportPropertyChanging("OrderDraftID");
                    _OrderDraftID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderDraftID");
                    OnOrderDraftIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderDraftID;
        partial void OnOrderDraftIDChanging(global::System.Int32 value);
        partial void OnOrderDraftIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                OnOrderIDChanging(value);
                ReportPropertyChanging("OrderID");
                _OrderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderID");
                OnOrderIDChanged();
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderDraftStatusID
        {
            get
            {
                return _OrderDraftStatusID;
            }
            set
            {
                OnOrderDraftStatusIDChanging(value);
                ReportPropertyChanging("OrderDraftStatusID");
                _OrderDraftStatusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderDraftStatusID");
                OnOrderDraftStatusIDChanged();
            }
        }
        private global::System.Int32 _OrderDraftStatusID;
        partial void OnOrderDraftStatusIDChanging(global::System.Int32 value);
        partial void OnOrderDraftStatusIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoDB", "FK_OrderDrafts_OrderDraftStatuses", "OrderDraftStatuses")]
        public OrderDraftStatuses OrderDraftStatuses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderDraftStatuses>("DemoDB.FK_OrderDrafts_OrderDraftStatuses", "OrderDraftStatuses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderDraftStatuses>("DemoDB.FK_OrderDrafts_OrderDraftStatuses", "OrderDraftStatuses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<OrderDraftStatuses> OrderDraftStatusesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderDraftStatuses>("DemoDB.FK_OrderDrafts_OrderDraftStatuses", "OrderDraftStatuses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<OrderDraftStatuses>("DemoDB.FK_OrderDrafts_OrderDraftStatuses", "OrderDraftStatuses", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoDB", "FK_OrderDrafts_Orders", "Orders")]
        public Orders Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Orders>("DemoDB.FK_OrderDrafts_Orders", "Orders").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Orders>("DemoDB.FK_OrderDrafts_Orders", "Orders").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Orders> OrdersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Orders>("DemoDB.FK_OrderDrafts_Orders", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Orders>("DemoDB.FK_OrderDrafts_Orders", "Orders", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoDB", Name="OrderDraftStatuses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderDraftStatuses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderDraftStatuses object.
        /// </summary>
        /// <param name="orderDraftStatusID">Initial value of the OrderDraftStatusID property.</param>
        /// <param name="orderDraftStatus">Initial value of the OrderDraftStatus property.</param>
        public static OrderDraftStatuses CreateOrderDraftStatuses(global::System.Int32 orderDraftStatusID, global::System.String orderDraftStatus)
        {
            OrderDraftStatuses orderDraftStatuses = new OrderDraftStatuses();
            orderDraftStatuses.OrderDraftStatusID = orderDraftStatusID;
            orderDraftStatuses.OrderDraftStatus = orderDraftStatus;
            return orderDraftStatuses;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderDraftStatusID
        {
            get
            {
                return _OrderDraftStatusID;
            }
            set
            {
                if (_OrderDraftStatusID != value)
                {
                    OnOrderDraftStatusIDChanging(value);
                    ReportPropertyChanging("OrderDraftStatusID");
                    _OrderDraftStatusID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderDraftStatusID");
                    OnOrderDraftStatusIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderDraftStatusID;
        partial void OnOrderDraftStatusIDChanging(global::System.Int32 value);
        partial void OnOrderDraftStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrderDraftStatus
        {
            get
            {
                return _OrderDraftStatus;
            }
            set
            {
                OnOrderDraftStatusChanging(value);
                ReportPropertyChanging("OrderDraftStatus");
                _OrderDraftStatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OrderDraftStatus");
                OnOrderDraftStatusChanged();
            }
        }
        private global::System.String _OrderDraftStatus;
        partial void OnOrderDraftStatusChanging(global::System.String value);
        partial void OnOrderDraftStatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoDB", "FK_OrderDrafts_OrderDraftStatuses", "OrderDrafts")]
        public EntityCollection<OrderDrafts> OrderDrafts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderDrafts>("DemoDB.FK_OrderDrafts_OrderDraftStatuses", "OrderDrafts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderDrafts>("DemoDB.FK_OrderDrafts_OrderDraftStatuses", "OrderDrafts", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoDB", Name="OrderPayments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderPayments : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderPayments object.
        /// </summary>
        /// <param name="orderPaymentID">Initial value of the OrderPaymentID property.</param>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="cashReceived">Initial value of the CashReceived property.</param>
        /// <param name="cashRefund">Initial value of the CashRefund property.</param>
        /// <param name="corporateFunding">Initial value of the CorporateFunding property.</param>
        public static OrderPayments CreateOrderPayments(global::System.Int32 orderPaymentID, global::System.Int32 orderID, global::System.Decimal amount, global::System.Decimal cashReceived, global::System.Decimal cashRefund, global::System.Decimal corporateFunding)
        {
            OrderPayments orderPayments = new OrderPayments();
            orderPayments.OrderPaymentID = orderPaymentID;
            orderPayments.OrderID = orderID;
            orderPayments.Amount = amount;
            orderPayments.CashReceived = cashReceived;
            orderPayments.CashRefund = cashRefund;
            orderPayments.CorporateFunding = corporateFunding;
            return orderPayments;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderPaymentID
        {
            get
            {
                return _OrderPaymentID;
            }
            set
            {
                if (_OrderPaymentID != value)
                {
                    OnOrderPaymentIDChanging(value);
                    ReportPropertyChanging("OrderPaymentID");
                    _OrderPaymentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderPaymentID");
                    OnOrderPaymentIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderPaymentID;
        partial void OnOrderPaymentIDChanging(global::System.Int32 value);
        partial void OnOrderPaymentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                OnOrderIDChanging(value);
                ReportPropertyChanging("OrderID");
                _OrderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderID");
                OnOrderIDChanged();
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CashReceived
        {
            get
            {
                return _CashReceived;
            }
            set
            {
                OnCashReceivedChanging(value);
                ReportPropertyChanging("CashReceived");
                _CashReceived = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CashReceived");
                OnCashReceivedChanged();
            }
        }
        private global::System.Decimal _CashReceived;
        partial void OnCashReceivedChanging(global::System.Decimal value);
        partial void OnCashReceivedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CashRefund
        {
            get
            {
                return _CashRefund;
            }
            set
            {
                OnCashRefundChanging(value);
                ReportPropertyChanging("CashRefund");
                _CashRefund = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CashRefund");
                OnCashRefundChanged();
            }
        }
        private global::System.Decimal _CashRefund;
        partial void OnCashRefundChanging(global::System.Decimal value);
        partial void OnCashRefundChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CorporateFunding
        {
            get
            {
                return _CorporateFunding;
            }
            set
            {
                OnCorporateFundingChanging(value);
                ReportPropertyChanging("CorporateFunding");
                _CorporateFunding = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CorporateFunding");
                OnCorporateFundingChanged();
            }
        }
        private global::System.Decimal _CorporateFunding;
        partial void OnCorporateFundingChanging(global::System.Decimal value);
        partial void OnCorporateFundingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateBilled
        {
            get
            {
                return _DateBilled;
            }
            set
            {
                OnDateBilledChanging(value);
                ReportPropertyChanging("DateBilled");
                _DateBilled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateBilled");
                OnDateBilledChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateBilled;
        partial void OnDateBilledChanging(Nullable<global::System.DateTime> value);
        partial void OnDateBilledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LineItemID
        {
            get
            {
                return _LineItemID;
            }
            set
            {
                OnLineItemIDChanging(value);
                ReportPropertyChanging("LineItemID");
                _LineItemID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LineItemID");
                OnLineItemIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LineItemID;
        partial void OnLineItemIDChanging(Nullable<global::System.Int32> value);
        partial void OnLineItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MailingID
        {
            get
            {
                return _MailingID;
            }
            set
            {
                OnMailingIDChanging(value);
                ReportPropertyChanging("MailingID");
                _MailingID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MailingID");
                OnMailingIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MailingID;
        partial void OnMailingIDChanging(Nullable<global::System.Int32> value);
        partial void OnMailingIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BillingID
        {
            get
            {
                return _BillingID;
            }
            set
            {
                OnBillingIDChanging(value);
                ReportPropertyChanging("BillingID");
                _BillingID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BillingID");
                OnBillingIDChanged();
            }
        }
        private Nullable<global::System.Int32> _BillingID;
        partial void OnBillingIDChanging(Nullable<global::System.Int32> value);
        partial void OnBillingIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoDB", "FK_OrderPayments_Orders", "Orders")]
        public Orders Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Orders>("DemoDB.FK_OrderPayments_Orders", "Orders").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Orders>("DemoDB.FK_OrderPayments_Orders", "Orders").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Orders> OrdersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Orders>("DemoDB.FK_OrderPayments_Orders", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Orders>("DemoDB.FK_OrderPayments_Orders", "Orders", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoDB", Name="OrderPromotions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderPromotions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderPromotions object.
        /// </summary>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="percentageDiscount">Initial value of the PercentageDiscount property.</param>
        /// <param name="monetaryDiscount">Initial value of the MonetaryDiscount property.</param>
        public static OrderPromotions CreateOrderPromotions(global::System.Int32 orderID, global::System.String number, global::System.Decimal percentageDiscount, global::System.Decimal monetaryDiscount)
        {
            OrderPromotions orderPromotions = new OrderPromotions();
            orderPromotions.OrderID = orderID;
            orderPromotions.Number = number;
            orderPromotions.PercentageDiscount = percentageDiscount;
            orderPromotions.MonetaryDiscount = monetaryDiscount;
            return orderPromotions;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Number
        {
            get
            {
                return _Number;
            }
            set
            {
                if (_Number != value)
                {
                    OnNumberChanging(value);
                    ReportPropertyChanging("Number");
                    _Number = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Number");
                    OnNumberChanged();
                }
            }
        }
        private global::System.String _Number;
        partial void OnNumberChanging(global::System.String value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PercentageDiscount
        {
            get
            {
                return _PercentageDiscount;
            }
            set
            {
                if (_PercentageDiscount != value)
                {
                    OnPercentageDiscountChanging(value);
                    ReportPropertyChanging("PercentageDiscount");
                    _PercentageDiscount = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PercentageDiscount");
                    OnPercentageDiscountChanged();
                }
            }
        }
        private global::System.Decimal _PercentageDiscount;
        partial void OnPercentageDiscountChanging(global::System.Decimal value);
        partial void OnPercentageDiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MonetaryDiscount
        {
            get
            {
                return _MonetaryDiscount;
            }
            set
            {
                if (_MonetaryDiscount != value)
                {
                    OnMonetaryDiscountChanging(value);
                    ReportPropertyChanging("MonetaryDiscount");
                    _MonetaryDiscount = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MonetaryDiscount");
                    OnMonetaryDiscountChanged();
                }
            }
        }
        private global::System.Decimal _MonetaryDiscount;
        partial void OnMonetaryDiscountChanging(global::System.Decimal value);
        partial void OnMonetaryDiscountChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoDB", "FK_OrderPromotions_Orders", "Orders")]
        public Orders Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Orders>("DemoDB.FK_OrderPromotions_Orders", "Orders").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Orders>("DemoDB.FK_OrderPromotions_Orders", "Orders").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Orders> OrdersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Orders>("DemoDB.FK_OrderPromotions_Orders", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Orders>("DemoDB.FK_OrderPromotions_Orders", "Orders", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoDB", Name="Orders")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Orders : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Orders object.
        /// </summary>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="totalPrice">Initial value of the TotalPrice property.</param>
        /// <param name="tax">Initial value of the Tax property.</param>
        /// <param name="shippingCost">Initial value of the ShippingCost property.</param>
        /// <param name="discount">Initial value of the Discount property.</param>
        /// <param name="listPrice">Initial value of the ListPrice property.</param>
        /// <param name="handling">Initial value of the Handling property.</param>
        public static Orders CreateOrders(global::System.Int32 orderID, global::System.Decimal totalPrice, global::System.Decimal tax, global::System.Decimal shippingCost, global::System.Decimal discount, global::System.Decimal listPrice, global::System.Decimal handling)
        {
            Orders orders = new Orders();
            orders.OrderID = orderID;
            orders.TotalPrice = totalPrice;
            orders.Tax = tax;
            orders.ShippingCost = shippingCost;
            orders.Discount = discount;
            orders.ListPrice = listPrice;
            orders.Handling = handling;
            return orders;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreated;
        partial void OnDateCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateUpdated
        {
            get
            {
                return _DateUpdated;
            }
            set
            {
                OnDateUpdatedChanging(value);
                ReportPropertyChanging("DateUpdated");
                _DateUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUpdated");
                OnDateUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateUpdated;
        partial void OnDateUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderStatusID
        {
            get
            {
                return _OrderStatusID;
            }
            set
            {
                OnOrderStatusIDChanging(value);
                ReportPropertyChanging("OrderStatusID");
                _OrderStatusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderStatusID");
                OnOrderStatusIDChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderStatusID;
        partial void OnOrderStatusIDChanging(Nullable<global::System.Int32> value);
        partial void OnOrderStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TotalPrice
        {
            get
            {
                return _TotalPrice;
            }
            set
            {
                OnTotalPriceChanging(value);
                ReportPropertyChanging("TotalPrice");
                _TotalPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalPrice");
                OnTotalPriceChanged();
            }
        }
        private global::System.Decimal _TotalPrice;
        partial void OnTotalPriceChanging(global::System.Decimal value);
        partial void OnTotalPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Tax
        {
            get
            {
                return _Tax;
            }
            set
            {
                OnTaxChanging(value);
                ReportPropertyChanging("Tax");
                _Tax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tax");
                OnTaxChanged();
            }
        }
        private global::System.Decimal _Tax;
        partial void OnTaxChanging(global::System.Decimal value);
        partial void OnTaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ShippingCost
        {
            get
            {
                return _ShippingCost;
            }
            set
            {
                OnShippingCostChanging(value);
                ReportPropertyChanging("ShippingCost");
                _ShippingCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShippingCost");
                OnShippingCostChanged();
            }
        }
        private global::System.Decimal _ShippingCost;
        partial void OnShippingCostChanging(global::System.Decimal value);
        partial void OnShippingCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Discount
        {
            get
            {
                return _Discount;
            }
            set
            {
                OnDiscountChanging(value);
                ReportPropertyChanging("Discount");
                _Discount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Discount");
                OnDiscountChanged();
            }
        }
        private global::System.Decimal _Discount;
        partial void OnDiscountChanging(global::System.Decimal value);
        partial void OnDiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ListPrice
        {
            get
            {
                return _ListPrice;
            }
            set
            {
                OnListPriceChanging(value);
                ReportPropertyChanging("ListPrice");
                _ListPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ListPrice");
                OnListPriceChanged();
            }
        }
        private global::System.Decimal _ListPrice;
        partial void OnListPriceChanging(global::System.Decimal value);
        partial void OnListPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Handling
        {
            get
            {
                return _Handling;
            }
            set
            {
                OnHandlingChanging(value);
                ReportPropertyChanging("Handling");
                _Handling = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Handling");
                OnHandlingChanged();
            }
        }
        private global::System.Decimal _Handling;
        partial void OnHandlingChanging(global::System.Decimal value);
        partial void OnHandlingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrderNumber
        {
            get
            {
                return _OrderNumber;
            }
            set
            {
                OnOrderNumberChanging(value);
                ReportPropertyChanging("OrderNumber");
                _OrderNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrderNumber");
                OnOrderNumberChanged();
            }
        }
        private global::System.String _OrderNumber;
        partial void OnOrderNumberChanging(global::System.String value);
        partial void OnOrderNumberChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoDB", "FK_OrderApprovals_Orders", "OrderApprovals")]
        public EntityCollection<OrderApprovals> OrderApprovals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderApprovals>("DemoDB.FK_OrderApprovals_Orders", "OrderApprovals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderApprovals>("DemoDB.FK_OrderApprovals_Orders", "OrderApprovals", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoDB", "FK_OrderDrafts_Orders", "OrderDrafts")]
        public EntityCollection<OrderDrafts> OrderDrafts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderDrafts>("DemoDB.FK_OrderDrafts_Orders", "OrderDrafts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderDrafts>("DemoDB.FK_OrderDrafts_Orders", "OrderDrafts", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoDB", "FK_OrderPayments_Orders", "OrderPayments")]
        public EntityCollection<OrderPayments> OrderPayments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderPayments>("DemoDB.FK_OrderPayments_Orders", "OrderPayments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderPayments>("DemoDB.FK_OrderPayments_Orders", "OrderPayments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoDB", "FK_OrderPromotions_Orders", "OrderPromotions")]
        public EntityCollection<OrderPromotions> OrderPromotions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderPromotions>("DemoDB.FK_OrderPromotions_Orders", "OrderPromotions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderPromotions>("DemoDB.FK_OrderPromotions_Orders", "OrderPromotions", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoDB", "FK_Orders_OrderStatuses", "OrderStatuses")]
        public OrderStatuses OrderStatuses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderStatuses>("DemoDB.FK_Orders_OrderStatuses", "OrderStatuses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderStatuses>("DemoDB.FK_Orders_OrderStatuses", "OrderStatuses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<OrderStatuses> OrderStatusesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderStatuses>("DemoDB.FK_Orders_OrderStatuses", "OrderStatuses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<OrderStatuses>("DemoDB.FK_Orders_OrderStatuses", "OrderStatuses", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoDB", Name="OrderStatuses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderStatuses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderStatuses object.
        /// </summary>
        /// <param name="orderStatusID">Initial value of the OrderStatusID property.</param>
        /// <param name="orderStatus">Initial value of the OrderStatus property.</param>
        /// <param name="rank">Initial value of the Rank property.</param>
        public static OrderStatuses CreateOrderStatuses(global::System.Int32 orderStatusID, global::System.String orderStatus, global::System.Int32 rank)
        {
            OrderStatuses orderStatuses = new OrderStatuses();
            orderStatuses.OrderStatusID = orderStatusID;
            orderStatuses.OrderStatus = orderStatus;
            orderStatuses.Rank = rank;
            return orderStatuses;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderStatusID
        {
            get
            {
                return _OrderStatusID;
            }
            set
            {
                if (_OrderStatusID != value)
                {
                    OnOrderStatusIDChanging(value);
                    ReportPropertyChanging("OrderStatusID");
                    _OrderStatusID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderStatusID");
                    OnOrderStatusIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderStatusID;
        partial void OnOrderStatusIDChanging(global::System.Int32 value);
        partial void OnOrderStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrderStatus
        {
            get
            {
                return _OrderStatus;
            }
            set
            {
                OnOrderStatusChanging(value);
                ReportPropertyChanging("OrderStatus");
                _OrderStatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OrderStatus");
                OnOrderStatusChanged();
            }
        }
        private global::System.String _OrderStatus;
        partial void OnOrderStatusChanging(global::System.String value);
        partial void OnOrderStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Rank
        {
            get
            {
                return _Rank;
            }
            set
            {
                OnRankChanging(value);
                ReportPropertyChanging("Rank");
                _Rank = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rank");
                OnRankChanged();
            }
        }
        private global::System.Int32 _Rank;
        partial void OnRankChanging(global::System.Int32 value);
        partial void OnRankChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoDB", "FK_Orders_OrderStatuses", "Orders")]
        public EntityCollection<Orders> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Orders>("DemoDB.FK_Orders_OrderStatuses", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Orders>("DemoDB.FK_Orders_OrderStatuses", "Orders", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
